"""Write a generated pipeline to disk: landing files, reference data, DAG log,
dbt project, expected anomalies and the data dictionary."""

import csv
import io
import json
from datetime import timedelta
from pathlib import Path
from typing import Any

import yaml

from app.pipeline import dbt_project
from app.pipeline.synthetic import (
    DUPLICATES,
    KEY_DRIFT,
    SCHEMA_DRIFT,
    SUBMITTERS,
    VOLUME,
    SyntheticPipeline,
)


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def _csv(rows: list[list[Any]]) -> str:
    buf = io.StringIO()
    csv.writer(buf, lineterminator="\n").writerows(rows)
    return buf.getvalue()


def _json(obj: Any) -> str:
    return json.dumps(obj, indent=2, sort_keys=True) + "\n"


def _yaml(obj: Any) -> str:
    return yaml.safe_dump(obj, sort_keys=False, width=100)


def write_sample(pipeline: SyntheticPipeline, out: Path) -> list[Path]:
    """Landing files, reference CSVs, DAG runs and expected anomalies under ``out``."""
    written = []
    landing = out / "landing"
    if landing.exists():
        for old in landing.glob("*.txt"):
            old.unlink()
    for f in pipeline.files:
        p = landing / f.name
        _write(p, f.render())
        written.append(p)

    start = pipeline.config.start.isoformat()
    ref = out / "reference"
    _write(
        ref / "outlet_location_map.csv",
        _csv(
            [["outlet_id", "location_id", "valid_from", "valid_to"]]
            + [[o, loc, "2025-01-01", ""] for o, loc in pipeline.outlets]
        ),
    )
    _write(
        ref / "submitter_registry.csv",
        _csv(
            [
                [
                    "submitter_id",
                    "submitter_name",
                    "channel",
                    "expected_daily_files",
                    "sla_hhmm",
                    "contact",
                ]
            ]
            + [[s.submitter_id, s.name, s.channel, 1, s.sla_hhmm, s.contact] for s in SUBMITTERS]
        ),
    )
    _write(
        ref / "file_arrivals.csv",
        _csv(
            [["file_name", "submitter_id", "business_date", "produced_at", "landed_at"]]
            + [
                [
                    f.name,
                    f.submitter_id,
                    f.business_date.isoformat(),
                    f.produced_at.strftime("%Y-%m-%dT%H:%M:%SZ"),
                    f.landed_at.strftime("%Y-%m-%dT%H:%M:%SZ"),
                ]
                for f in pipeline.files
            ]
        ),
    )
    _write(
        out / "airflow" / "dag_runs.json",
        _json({"dag_id": "retail_txn_daily", "window_start": start, "runs": pipeline.dag_runs}),
    )
    _write(out / "expected_anomalies.json", _json(pipeline.expected))
    written += [
        ref / "outlet_location_map.csv",
        ref / "submitter_registry.csv",
        ref / "file_arrivals.csv",
        out / "airflow" / "dag_runs.json",
        out / "expected_anomalies.json",
    ]
    return written


def write_dbt(pipeline: SyntheticPipeline, dbt_dir: Path) -> list[Path]:
    end = pipeline.config.start + timedelta(days=pipeline.config.days)
    files = {
        dbt_dir
        / "dbt_project.yml": _yaml(
            {
                "name": dbt_project.PROJECT,
                "version": "1.0.0",
                "config-version": 2,
                "profile": "retail_recon",
                "model-paths": ["models"],
            }
        ),
        dbt_dir / "models" / "sources.yml": _yaml(dbt_project.sources_yaml()),
        dbt_dir
        / "target"
        / "manifest.json": _json(dbt_project.manifest(f"{end.isoformat()}T05:00:00Z")),
    }
    for m in dbt_project.MODELS:
        files[dbt_dir / "models" / m["path"]] = _yaml(dbt_project.model_yaml(m))
    for path, text in files.items():
        _write(path, text)
    return list(files)


def data_dictionary(pipeline: SyntheticPipeline) -> str:
    cfg, exp = pipeline.config, pipeline.expected
    s = exp["summary"]
    lines = [
        "# Data dictionary",
        "",
        "Generated by `scripts/generate_synthetic_pipeline.py "
        f"--seed {cfg.seed}`. Do not edit by hand; rerun the generator.",
        "",
        f"Window: {cfg.days} business days from {cfg.start.isoformat()}. "
        f"{s['files']} landing files, {s['rows']:,} rows including one resend.",
        "",
        "## transactions",
        "",
        "One row per line item. Loaded from pipe-delimited submitter files in "
        "`data/sample/landing/`; the loader adds `submitter_file_name`.",
        "",
        "| Column | Type | Description |",
        "|---|---|---|",
    ]
    for c in dbt_project.RAW_COLUMNS:
        lines.append(f"| `{c['name']}` | {c['data_type']} | {c['description']} |")
    lines += [
        "",
        "Dedup key: `transaction_id`, `channel_basket_id`, `upc_code`. "
        "When a key appears in several files, the row from the file with the latest "
        "`YYYYMMDD_HHMM` in its name wins.",
        "",
        "## Reference data",
        "",
        "| File | What it holds |",
        "|---|---|",
        "| `reference/outlet_location_map.csv` | Canonical outlet to location mapping, "
        f"{len(pipeline.outlets)} locations, one to one. |",
        "| `reference/submitter_registry.csv` | The four submitters, their channel and SLA. |",
        "| `reference/file_arrivals.csv` | When each file was produced and when it landed. |",
        "| `airflow/dag_runs.json` | `retail_txn_daily` run history with per-task state, "
        "timings and log lines. |",
        "| `expected_anomalies.json` | Exact size of every planted anomaly. Tests read this. |",
        "",
        "## Submitters",
        "",
        "| submitter_id | name | channel | share of rows | SLA (UTC, next morning) |",
        "|---|---|---|---|---|",
    ]
    for sub in SUBMITTERS:
        cells = [sub.submitter_id, sub.name, sub.channel, f"{sub.share:.0%}", sub.sla_hhmm]
        lines.append("| " + " | ".join(cells) + " |")
    lines += ["", "## Planted anomalies", ""]
    if KEY_DRIFT in exp:
        k = exp[KEY_DRIFT]
        lines += [
            "### Key drift",
            "",
            f"`{k['location_id']}` reports under its canonical `{k['canonical_outlet_id']}` and "
            f"under `{k['drifted_outlet_id']}`, which is not in `outlet_location_map`. "
            "Whole baskets drift together, as if some registers had the wrong store profile.",
            "",
            f"- Drifted rows: **{k['drifted_rows']}** of {k['rows_in_window']:,} deduplicated "
            f"rows ({k['drift_rate']:.1%}).",
            "- Detect: group by `location_id` per business date, flag more than one "
            "`outlet_id`, compare against the map.",
            f"- Expected: `key_drift` finding from the Reconciliation agent, severity "
            f"{k['expected_severity']}.",
            "",
        ]
    if DUPLICATES in exp:
        d = exp[DUPLICATES]
        lines += [
            "### Duplicate submission",
            "",
            f"{d['submitter_id']} resent its {d['business_date']} file. `{d['resend_file']}` "
            f"contains every key from `{d['original_file']}`; {d['changed_rows']} rows carry a "
            "corrected `qty` and `amount`. The resend landed after that night's DAG run, so "
            "dedupe never saw it.",
            "",
            f"- Duplicate keys: **{d['duplicate_keys']}**, superseded rows: "
            f"**{d['superseded_rows']}**, rows whose values changed: **{d['changed_rows']}**.",
            "- Detect: rank rows per dedup key by file timestamp; everything below rank 1 "
            "is superseded.",
            f"- Expected: `duplicate_submission` finding from the Reconciliation agent, severity "
            f"{d['expected_severity']}.",
            "",
        ]
    if SCHEMA_DRIFT in exp:
        sd = exp[SCHEMA_DRIFT]
        lines += [
            "### Schema drift",
            "",
            f"`{sd['file']}` ({sd['business_date']}) renamed `{sd['missing_columns'][0]}` to "
            f"`{sd['unexpected_columns'][0]}`. The loader maps by name, so its "
            f"{sd['affected_rows']} rows land with a null `channel_basket_id`, and "
            f"`{sd['failed_task']}` fails that night with a `ContractViolation`.",
            "",
            "- Detect: diff each batch header against the `raw.transactions` contract in the "
            "dbt manifest; confirm with the failed task log.",
            f"- Expected: `schema_drift` finding from the Data-Quality agent, severity "
            f"{sd['expected_severity']} (a dedup-key column was lost).",
            "",
        ]
    if VOLUME in exp:
        v = exp[VOLUME]
        lines += [
            "### Volume anomaly",
            "",
            f"{v['submitter_id']}'s {v['business_date']} file `{v['file']}` has {v['rows']} rows "
            f"against a trailing 7-day average of {v['trailing_avg_7d']} "
            f"({v['pct_below_trailing']:.0%} below). It also landed "
            f"{v['minutes_after_sla']} minutes after the submitter SLA, so the sensor waited.",
            "",
            "- Detect: per-submitter daily row count against the trailing 7-day average; "
            "check sensor duration and landing time in the DAG history.",
            f"- Expected: `volume_anomaly` finding from the Data-Quality agent, severity "
            f"{v['expected_severity']}.",
            "",
        ]
    lines += [
        "## Not anomalies",
        "",
        "Daily volume varies by up to 5% per submitter, about 2% of lines are returns with "
        "negative `qty`, and file production times move around inside each submitter's window. "
        "None of that should produce a finding.",
        "",
    ]
    return "\n".join(lines)


def write_all(pipeline: SyntheticPipeline, out: Path, dbt_dir: Path, dictionary: Path) -> None:
    write_sample(pipeline, out)
    write_dbt(pipeline, dbt_dir)
    _write(dictionary, data_dictionary(pipeline))
